# Generated by Django 3.1.5 on 2021-01-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_calendar', '0002_auto_20210108_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant_calendar.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.UUIDField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
