# Generated by Django 3.1.5 on 2021-01-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_calendar', '0003_auto_20210108_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='companies',
            new_name='company_i',
        ),
        migrations.RenameField(
            model_name='conferenceroom',
            old_name='companies',
            new_name='company_i',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='companies',
            new_name='company_i',
        ),
    ]
