# Generated by Django 3.1.5 on 2021-01-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_calendar', '0004_auto_20210108_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='partcipants',
            new_name='participants',
        ),
    ]
