# Generated by Django 3.1.5 on 2021-01-08 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_calendar', '0005_auto_20210108_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='company_i',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant_calendar.company'),
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='company_i',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant_calendar.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_i',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant_calendar.company'),
        ),
    ]
